apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc
spec:
  gateways:
    - istio-rollout-gateway
  hosts:
    - "*"
  http:
    - route:
      - destination:
          host: stable-svc
        weight: 95
      - destination:
          host: canary-svc
        weight: 5